### PR TITLE
Use DOMMatrix transforms to convert points between spaces.

### LINKED ISSUE #1420: Coordinate conversion doesn't work with complex 3d transforms.
When using a complex transform, e.g. perspecttive or transform-origins not in the center of elements, the coordinate conversion does not correctly take that into account.

See as an example how cards shift when dropping them on this perspective demo:
https://virtualtabletop.io/perspective

### PR DESCRIPTION
**Pull request by flackr**
This supports arbitrarily complex transformations including perspective and also leans on the browser to do the conversion between coordinate spaces. Fixes #1420.

### CODE REVIEW

**Comment by ArnoldSmith86** [comment]
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1421/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1421-pr-test`.

**Comment by flackr** [comment]
For comparison, you can see the difference when dragging cards on https://test.virtualtabletop.io/PR-1421/pr-test compared to https://virtualtabletop.io/perspective

File: client/js/geometry.js [hunk 1]
```diff
@@ -18,12 +18,58 @@ export function getOffset(origin, target) {
...
+  let t = new DOMPoint(10, 10);
+  while (elem) {
+    transform.preMultiplySelf(getElementTransform(elem));
+    elem = elem.offsetParent;
   }
+  return transform;
+}
+
+function parseLengths(str) {
+  return str.split(' ').map(s => parseFloat(s))
```
Comment (flackr) [inline client/js/geometry.js:32]: I decided to simply split on ' ' here (compared to the initial commit) since the computed `transformOrigin` and `perspectiveOrigin` can always be expected to be `###px ###px` and it should be more efficient than a regular expression.

File: client/js/geometry.js [hunk 2]
```diff
@@ -18,12 +18,58 @@ export function getOffset(origin, target) {
...
+
+export function getPointOnPlane(transform, x, y) {
+  const inv = transform.inverse();
+  const p0 = dehomogenize(inv.transformPoint(new DOMPoint(x, y, 0)));
+  // Get transformed direction vector of ray in (0, 0, 1) direction.
+  let dir = dehomogenize(inv.transformPoint(new DOMPoint(x, y, 1)));
+  dir.x -= p0.x;
+  dir.y -= p0.y;
+  dir.z -= p0.z;
+  // If the projected line is parallel with the plane, no intersection point can be determined.
```
Comment (flackr) [inline client/js/geometry.js:47]: Note we generally shouldn't hit this case since it is invalid (and for dragging you shouldn't be able to hit test to a plane / widget that is completely showing its side to you as it is not visible), but we may want to do something to more gracefully handle the null return so it doesn't result in a JS error.

Comment (flackr) [reply client/js/geometry.js:47]: Done in latest commit.

**Review by ArnoldSmith86 — APPROVED** [review]
If you're sure that this works on a reasonable range of browsers, this seems like a great improvement.

I have no clue about all the stuff you do but the code seems to be in the right place and I don't spot any obvious mistakes.

**Comment by flackr** [comment]
> If you're sure that this works on a reasonable range of browsers, this seems like a great improvement.

Thanks! Yeah I'm fairly certain this is supported in any browser released in the last 5 years. Also, if needed it wouldn't be hard to polyfill the portion of DOMMatrix used here.

@96LawDawg you tested this earlier, would you consider this reviewed from a testing standpoint as well?

**Comment by 96LawDawg** [comment]
It really is an amazing effect.  I tested it on Chrome, Edge, and Firefox on my PC.  I tested it on Safari on iOS (current-ish version).  Everything worked and looked the same between all browsers.

The hitbox area at the top of the screen is pretty large and depending on where I have my mouse in relation to the card, I can get some results that are a bit off the table, but you can usually tell that is going to happen because of the way the holder acts.  See screenshot.

Also, I decided to try it with a game that uses grids: Dominoes.  Less great results there.  The horizontal grid worked fine everywhere except the top (literally an edge case).  The vertical grid never worked right, leaving a small gap between all the tiles, or overlapping slightly.  Seemed strange to me that there was a difference.  Would like for you to explore that more if possible before approving.  I left the dominoes demo in the PR test room.

**Comment by flackr** [comment]
> The hitbox area at the top and sides of the screen are pretty large and depending on where I have my mouse in relation to the card, I can get some results that are a bit off the table

So I suspect you were dragging from the top of the card, and just barely had the middle of the card over the "table"? The drop target is determined before the transformation (same as before FWIW), however, I suspect if I transform the dragged card to where it would be after transformation that the drop target determination would be spot for where the card would land in that layer.

Would you be okay with this as a followup? It is an existing issue that the drop targeting doesn't really account for the transformation that will be done to a card when it's dropped.

> Also, I decided to try it with a game that uses grids: Dominoes. Less great results there. The horizontal grid worked fine everywhere except the top (literally an edge case). The vertical grid never worked right, leaving a small gap between all the tiles, or overlapping slightly. Seemed strange to me that there was a difference. Would like for you to explore that more if possible before approving. I left the dominoes demo in the PR test room.

Could you help me understand what I should be looking for? I see the same misalignment when testing on the main branch, https://virtualtabletop.io/pr-1421-pr-test-baseline. I suspect that grid snapping may need some overall rethinking to work with perspective, i.e. it would have to snap to positions in the perspective grid in order to correspond to drop positions correctly.

**Comment by 96LawDawg** [comment]
> So I suspect you were dragging from the top of the card, and just barely had the middle of the card over the "table"? The drop target is determined before the transformation (same as before FWIW), however, I suspect if I transform the dragged card to where it would be after transformation that the drop target determination would be spot for where the card would land in that layer.
> 
> Would you be okay with this as a followup? It is an existing issue that the drop targeting doesn't really account for the transformation that will be done to a card when it's dropped.

I did have the pointer near the top, but the _bottom_ of the card was just barely over the table.  Either way, no big deal.  I don't have a problem with this, but if refinements are possible, that would be great, but not necessary.


> > Also, I decided to try it with a game that uses grids: Dominoes. Less great results there. The horizontal grid worked fine everywhere except the top (literally an edge case). The vertical grid never worked right, leaving a small gap between all the tiles, or overlapping slightly. Seemed strange to me that there was a difference. Would like for you to explore that more if possible before approving. I left the dominoes demo in the PR test room.
> 
> Could you help me understand what I should be looking for? I see the same misalignment when testing on the main branch, https://virtualtabletop.io/pr-1421-pr-test-baseline. I suspect that grid snapping may need some overall rethinking to work with perspective, i.e. it would have to snap to positions in the perspective grid in order to correspond to drop positions correctly.

It's the gap between the tiles going vertically.  It is not present on production but is present in this PR.

PR 1421

Production

**Comment by flackr** [comment]
Okay I see. I think I know what's leading to the issue, and how it's related to more correct drop targets. This doesn't reproduce on production on that particular example only because production completely ignores the perspective but it does reproduce with a rotation - see my updated test on production: https://virtualtabletop.io/pr-1421-pr-test-baseline

The issue looks like we snap in untransformed coordinates (both before and after this PR), and then the transformation to local coordinate space can result in the tiles no longer being aligned.

**Comment by flackr** [comment]
I think that we could fix this by making the snapping code snap in the drop target's coordinate space rather than the global space, but this is also not new to this issue, just new in that this issue now also includes perspective in the client to local coordinate mapping.

**Comment by 96LawDawg** [comment]
> I think that we could fix this by making the snapping code snap in the drop target's coordinate space rather than the global space, but this is also not new to this issue, just new in that this issue now also includes perspective in the client to local coordinate mapping.

Yes, but a good time to fix it if we can.  Because perspective wasn't really possible before now so the limits of it had not been tested.

**Comment by flackr** [comment]
> Because perspective wasn't really possible before now so the limits of it had not been tested.

FWIW scale and rotation are both currently broken for snapping (see my demos above). Do we need to gate this particular coordinate mapping improvement on fixing pre-existing snapping issues?

**Comment by 96LawDawg** [comment]
> > Because perspective wasn't really possible before now so the limits of it had not been tested.
> 
> FWIW scale and rotation are both currently broken for snapping (see my demos above). Do we need to gate this particular coordinate mapping improvement on fixing pre-existing snapping issues?

No.  Not at all.  When I raised the issue, I thought this was something special to perspective.  But you are right that scale (and I never thought about rotation) greatly screw with coordinate map issues currently.

**Comment by flackr** [comment]
I filed #1440 to track fixing that issue. I think it will be a relatively simple change.

**Review by 96LawDawg — APPROVED** [review]
Approved through test

**Comment by flackr** [comment]
Woops, lost the reviews by adding a merge commit!
